logo_title: 读书写字

style: white

favicon: /favicon.ico

menu:
  文章: /posts
  我: /about
  搜索: /search

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: true
  appId: CmCti21ooOOIzFOhEyFkFvR0-gzGzoHsz
  appKey: FqiyUqbg7McKN2eG0MCewupf

highlight:
  enable: false